#!/usr/bin/env python3
"""Build a Map-of-Content index (_index.md) from the repo's markdown.

Second-brain indexer for Magnet Baron. Globs the repo's markdown, extracts each
file's title (first H1 or frontmatter `title:`) and a one-line summary (first
non-empty prose line), and writes a linked _index.md grouped by top-level
directory. Read-only except for the output file. Deterministic and idempotent:
no timestamps embedded, entries sorted, so re-running only changes real content.

Usage:
    python3 .claude/skills/doctrine-sync/scripts/build_index.py [--root .] [--out _index.md]

Stdlib only. No network.
"""
import argparse
import os
import re
import sys

# Directories we never index (noise / not doctrine).
SKIP_DIRS = {".git", ".claude", ".cursor", "node_modules", "__pycache__"}
# Files we never index.
SKIP_FILES = {"_index.md"}

FRONTMATTER_TITLE = re.compile(r"^title:\s*(.+?)\s*$", re.MULTILINE)
H1 = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)


def discover(root):
    """Yield repo-relative paths to .md files, skipping SKIP_DIRS."""
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            if not name.endswith(".md"):
                continue
            if name in SKIP_FILES:
                continue
            full = os.path.join(dirpath, name)
            yield os.path.relpath(full, root)


def read_meta(path):
    """Return (title, summary) for a markdown file."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    except OSError as exc:
        return (os.path.basename(path), f"(unreadable: {exc})")

    title = None
    body = text
    # Strip a leading YAML frontmatter block, pulling `title:` if present.
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            fm = text[3:end]
            m = FRONTMATTER_TITLE.search(fm)
            if m:
                title = m.group(1).strip().strip('"').strip("'")
            body = text[end + 4:]

    if not title:
        m = H1.search(body)
        if m:
            title = m.group(1).strip()
    if not title:
        title = os.path.splitext(os.path.basename(path))[0]

    # First non-empty, non-heading, non-rule prose line as the summary.
    summary = ""
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("---") or s.startswith("|"):
            continue
        summary = re.sub(r"[*_`>]+", "", s)
        break
    if len(summary) > 160:
        summary = summary[:157].rstrip() + "..."
    return (title, summary)


def group_of(relpath):
    """Group key = first path segment, or 'root' for top-level files."""
    parts = relpath.split(os.sep)
    return parts[0] if len(parts) > 1 else "root"


GROUP_TITLES = {
    "root": "Doctrine (repo root)",
    "roles": "Roles",
    "llms-subtree": "AI / LLM references",
    "docs": "Docs",
}


def build(root, out):
    files = list(discover(root))
    groups = {}
    for rel in files:
        groups.setdefault(group_of(rel), []).append(rel)

    lines = ["# Index (Map of Content)", ""]
    lines.append(
        "Generated by `doctrine-sync` from the repo markdown. Git is the source "
        "of truth; this index is derived — links only, never inlined content. "
        "Regenerate with `build_index.py` after doctrine changes."
    )
    lines.append("")
    for key in sorted(groups, key=lambda k: (k != "root", k)):
        heading = GROUP_TITLES.get(key, key.replace("-", " ").replace("/", " / ").title())
        lines.append(f"## {heading}")
        lines.append("")
        for rel in sorted(groups[key]):
            title, summary = read_meta(os.path.join(root, rel))
            link = rel.replace(os.sep, "/")
            if summary:
                lines.append(f"- [{title}]({link}) — {summary}")
            else:
                lines.append(f"- [{title}]({link})")
        lines.append("")

    out_path = os.path.join(root, out)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")
    return out_path, len(files)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Build _index.md Map of Content.")
    ap.add_argument("--root", default=".", help="repo root to scan (default: .)")
    ap.add_argument("--out", default="_index.md", help="output file, relative to root")
    args = ap.parse_args(argv)

    root = os.path.abspath(args.root)
    if not os.path.isdir(root):
        print(f"error: root not a directory: {root}", file=sys.stderr)
        return 2
    out_path, n = build(root, args.out)
    print(f"wrote {out_path} indexing {n} markdown files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
