#!/usr/bin/env python3
"""Link installed skills and generate role-scoped Codex skill configuration."""
from __future__ import annotations

import argparse
import json
import os
import tempfile
from pathlib import Path


HERE = Path(__file__).resolve().parent
REPO = HERE.parent
REGISTRY = HERE / "registry.json"


def load_registry(path: Path = REGISTRY) -> dict:
    data = json.loads(path.read_text())
    if data.get("schema_version") != 1:
        raise ValueError("skills registry must use schema_version 1")
    sources = data.get("sources")
    routes = data.get("routes")
    if not isinstance(sources, dict) or not sources:
        raise ValueError("skills registry requires sources")
    if not isinstance(routes, dict) or not routes:
        raise ValueError("skills registry requires routes")

    catalog: list[str] = []
    for source_name, source in sources.items():
        if not source.get("repository") or not source.get("revision"):
            raise ValueError(f"{source_name}: repository and revision are required")
        skills = source.get("skills")
        if not isinstance(skills, list) or not skills or len(skills) != len(set(skills)):
            raise ValueError(f"{source_name}: skills must be a non-empty unique list")
        catalog.extend(skills)
    if len(catalog) != len(set(catalog)):
        raise ValueError("a skill may belong to only one source")

    catalog_set = set(catalog)
    for route_name, route in routes.items():
        if route.get("activation") not in {"disabled", "progressive"}:
            raise ValueError(f"{route_name}: activation must be disabled or progressive")
        skills = route.get("skills")
        if not isinstance(skills, list) or len(skills) != len(set(skills)):
            raise ValueError(f"{route_name}: skills must be a unique list")
        unknown = set(skills) - catalog_set
        if unknown:
            raise ValueError(f"{route_name}: unknown skills: {sorted(unknown)}")
        if route["activation"] == "disabled" and skills:
            raise ValueError(f"{route_name}: disabled routes cannot enable skills")
    return data


def catalog(data: dict) -> list[str]:
    return [skill for source in data["sources"].values() for skill in source["skills"]]


def q(value: str) -> str:
    return json.dumps(value)


def skill_entries(skills: list[str], universal_root: Path, enabled: bool) -> str:
    blocks = []
    for name in skills:
        path = universal_root / name / "SKILL.md"
        blocks.append(
            "[[skills.config]]\n"
            f"path = {q(str(path))}\n"
            f"enabled = {'true' if enabled else 'false'}"
        )
    return "\n\n".join(blocks) + "\n"


def agent_toml(name: str, description: str, instructions: str, skills: list[str], universal_root: Path, read_only: bool) -> str:
    lines = [
        f"name = {q(name)}",
        f"description = {q(description)}",
        f"sandbox_mode = {q('read-only' if read_only else 'workspace-write')}",
        f"developer_instructions = {q(instructions)}",
        "",
        skill_entries(skills, universal_root, True).rstrip(),
        "",
    ]
    return "\n".join(lines)


def expected_files(data: dict, universal_root: Path) -> dict[Path, str]:
    all_skills = catalog(data)
    accessibility = data["routes"]["mobile-accessibility-reviewer"]["skills"]
    return {
        REPO / ".codex/config.toml": (
            "# Generated by skills/sync.py. Dispatch and ordinary agents do not load mobile skills.\n\n"
            + skill_entries(all_skills, universal_root, False)
        ),
        REPO / ".codex/agents/mb-mobile-accessibility-reviewer.toml": agent_toml(
            "mb-mobile-accessibility-reviewer",
            "Read-only iOS accessibility reviewer for UIKit, SwiftUI, VoiceOver, Dynamic Type, and assistive-technology work.",
            "Review only the assigned iOS accessibility scope. Load ios-accessibility, inspect evidence, and return ship, fix-list, or blocked. Do not edit files or treat automated checks as a substitute for manual assistive-technology testing.",
            accessibility,
            universal_root,
            True,
        ),
    }


def write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    with os.fdopen(fd, "w") as handle:
        handle.write(text)
    os.replace(tmp, path)


def sync(check: bool = False) -> None:
    data = load_registry()
    installed_root = Path(data["installed_root"]).expanduser()
    universal_root = Path(data["universal_root"]).expanduser()
    repo_skill_root = REPO / ".agents/skills"
    problems = []

    for name in catalog(data):
        installed = installed_root / name
        universal = universal_root / name
        repo_link = repo_skill_root / name
        if not (installed / "SKILL.md").is_file():
            problems.append(f"missing installed skill: {installed}")
            continue
        for link, target in ((universal, installed), (repo_link, universal)):
            if link.is_symlink() and link.resolve() == target.resolve():
                continue
            if link.exists() or link.is_symlink():
                problems.append(f"collision or wrong target: {link}")
            elif not check:
                link.parent.mkdir(parents=True, exist_ok=True)
                link.symlink_to(target, target_is_directory=True)

    for path, text in expected_files(data, universal_root).items():
        if path.exists() and path.read_text() == text:
            continue
        if check:
            problems.append(f"missing or stale generated file: {path}")
        else:
            write_atomic(path, text)

    if problems:
        raise SystemExit("\n".join(problems))
    action = "verified" if check else "linked and generated"
    print(f"{action} {len(catalog(data))} skills across {len(data['routes'])} routes")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sync(check=args.check)


if __name__ == "__main__":
    main()
